Define request collapsing
httpwg/http-core pull request #480
Opened 2020-10-22 02:58 UTC by mnot

Fixes #475

2020-10-22 03:56 UTC, reschke requested changes

2020-10-22 03:56 UTC, reschke commented on draft-ietf-httpbis-cache-latest.xml
> +   requests, provided that it is allowed to reuse that response for the requests
Maybe "A response that is stored or storable can be used to satisfy multiple..." ?

2020-10-22 04:03 UTC, mnot commented on draft-ietf-httpbis-cache-latest.xml
> +   A response that is stored or can be stored can be used to satisfy multiple
```suggestion
   A response that is stored or storable can be used to satisfy multiple
```

2020-10-22 04:11 UTC, reschke approved these changes

2020-10-29 07:35 UTC, reschke reviewed
Maybe add a minimal explanation of "collapse"?

2020-10-29 07:35 UTC, mnot commented on draft-ietf-httpbis-cache-latest.xml
> +   in question. This enables caches to "collapse" multiple requests into a single forward
add a parenthetical more fully describing what's happening

2020-10-29 07:36 UTC, royfielding approved these changes

2020-11-12 05:38 UTC, mnot commented on draft-ietf-httpbis-cache-latest.xml
> +   in question. This enables caches to "collapse" multiple requests into a single forward
Looking at this again, "multiple requests into a single forward request" says all that needs to be, I think. I will change "requests" to "incoming requests" to clarify.

2020-11-12 05:39 UTC, mnot commented on draft-ietf-httpbis-cache-latest.xml
> +   in question. This enables caches to "collapse" multiple requests into a single forward
```suggestion
   in question. This enables caches to "collapse" multiple incoming requests into a single forward
```

2020-11-12 05:40 UTC, merged