Relax invalidation on Location and Content-Location
httpwg/http-core pull request #486
Opened 2020-10-22 04:01 UTC by mnot

Fixes #478.

2020-10-22 04:03 UTC, reschke approved these changes

2020-10-29 07:27 UTC, mnot commented on draft-ietf-httpbis-cache-latest.xml
>  <t>
```suggestion
```

2020-10-29 07:29 UTC, mnot commented on draft-ietf-httpbis-cache-latest.xml
> +   if the host part of the URI to be invalidated differs from the host part of the target URI
change to origin, not host; list in changes; write some tests

2020-11-12 07:06 UTC, mnot commented on draft-ietf-httpbis-cache-latest.xml
> +   Cache invalidation of Location and Content-Location is disallowed
```suggestion
   Cache invalidation of the URIs in Location and Content-Location is disallowed
```

2020-11-12 07:10 UTC, mnot commented
@reschke @royfielding please double-check; I think we said this was ok after some tweaks.

2020-11-12 13:17 UTC, reschke requested changes

2020-11-12 13:17 UTC, reschke commented on draft-ietf-httpbis-cache-latest.xml
> +   fields (if present) are candidates for invalidation; other URLs might be discovered
```suggestion
   fields (if present) are candidates for invalidation; other URIs might be discovered
```

(consistency)

2020-11-12 18:31 UTC, royfielding approved these changes

2020-11-12 18:31 UTC, merged