Mention Structured Fields
httpwg/http-core pull request #621
Opened 2020-12-31 02:24 UTC by mnot

Including a re-org of Considerations for New Fields

Fixes #539.

2020-12-31 17:33 UTC, reschke approved these changes

2020-12-31 17:33 UTC, reschke commented on draft-ietf-httpbis-semantics-latest.xml
> +   target="field-values"/>) are additionally advised document how to treat
...to document...

2020-12-31 22:47 UTC, royfielding commented on draft-ietf-httpbis-semantics-latest.xml
> +   widely used need to be more carefully documented, to ensure interoperability.
```suggestion
   While they can be used in an ad hoc fashion, fields that are intended for
   wider use need to be carefully documented to ensure interoperability.
```

2020-12-31 23:05 UTC, royfielding requested changes

2020-12-31 23:05 UTC, royfielding commented on draft-ietf-httpbis-semantics-latest.xml
> +   list values.
```suggestion
   Therefore, authors are advised to delimit or encode values that contain
   commas (e.g., with the <x:ref>quoted-string</x:ref> rule of
   <xref target="quoted.strings"/>, the String data type of
   <xref target="RFCSTRF"/>), or a field-specific encoding).
   This ensures that commas within field data are not confused
   with the commas that delimit a list value.
```

2020-12-31 23:05 UTC, royfielding commented on draft-ietf-httpbis-semantics-latest.xml
> +   inside quoted strings, and so can be reliably parsed, even when multiple
```suggestion
   inside quoted strings, which can be reliably parsed even when multiple
```

2021-01-02 06:22 UTC, royfielding approved these changes

2021-01-02 06:23 UTC, merged