Tweak core semantics
httpwg/http-core pull request #631
Opened 2021-01-04 00:42 UTC by mnot

Commas were a bit overwhelming

2021-01-04 07:47 UTC, reschke requested changes

2021-01-04 07:47 UTC, reschke commented on draft-ietf-httpbis-semantics-latest.xml
> +   (<xref target="resources"/>) - regardless of its type, nature, or
```suggestion
   (<xref target="resources"/>) &mdash; regardless of its type, nature, or
```

2021-01-04 07:47 UTC, reschke commented on draft-ietf-httpbis-semantics-latest.xml
> +   implementation - by sending messages that manipulate or transfer
```suggestion
   implementation &mdash; by sending messages that manipulate or transfer
```

2021-01-05 10:02 UTC, reschke approved these changes

2021-01-05 16:47 UTC, royfielding approved these changes

2021-01-05 16:48 UTC, merged