Clarify how multiple validators are handled
httpwg/http-core pull request #666
Opened 2021-01-08 02:25 UTC by mnot

Fixes #659

2021-01-08 14:13 UTC, reschke commented on draft-ietf-httpbis-cache-latest.xml
>       identifies the selected representation for update. All the stored
```suggestion
     identify the selected representation for update. All the stored
```

2021-01-08 14:13 UTC, reschke commented on draft-ietf-httpbis-cache-latest.xml
>       identifies the selected representation for update. All the stored
```suggestion
     identify the selected representation for update. All the stored
```

2021-01-08 14:14 UTC, reschke commented on draft-ietf-httpbis-cache-latest.xml
> +     validator correspond to one of the cache's stored responses, then the most
```suggestion
     validators correspond to one of the cache's stored responses, then the most
```

2021-01-08 14:16 UTC, reschke commented
There's still a difference when the response mixes strong and weak validators, right? If both types are present, the weak ones would get ignored. Is that intentional?

2021-01-08 18:57 UTC, royfielding commented
> There's still a difference when the response mixes strong and weak validators, right? If both types are present, the weak ones would get ignored. Is that intentional?

Yes, that is intentional.

2021-01-08 19:12 UTC, royfielding requested changes
This is a little hard to understand because the original text assumes we are talking about a single strong etag and a single weak LM time.

In theory, we should either require that one match or require that they all match. In practice, the entity-tag is definitive and all the other validators are simple string match if and only if no entity-tag is present.

I don't know if we want to monkey patch this, or just throw out the existing text and point to Semantics.

2021-01-08 19:12 UTC, royfielding commented on draft-ietf-httpbis-cache-latest.xml
> +     responses with the same strong validators are identified for update. If
```suggestion
     responses with one of those same strong validators are identified for update. If
```

2021-01-08 19:12 UTC, royfielding commented on draft-ietf-httpbis-cache-latest.xml
> +     <xref target="weak.and.strong.validators"/>), then those strong validators
```suggestion
     <xref target="weak.and.strong.validators"/>), then each of those strong validators
```

2021-01-09 02:36 UTC, royfielding approved these changes

2021-01-10 06:34 UTC, reschke approved these changes

2021-01-10 06:34 UTC, merged