Specify IMS and IUS like INM and If-Match
httpwg/http-core pull request #670
Opened 2021-01-11 10:39 UTC by mnot

Fixes #665

2021-01-11 15:47 UTC, reschke approved these changes
I don't think this change is needed, but if you prefer it this way...

2021-01-12 04:47 UTC, royfielding requested changes
I prefer the original, particularly given that these are requirements.

2021-01-12 06:07 UTC, mnot commented
They're still requirements, and without the changes, we don't explicitly say how to evaluate the conditionals; elsewhere (e.g., [precedence](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#precedence) we refer to them as evaluating to either true or false, hence these changes.

2021-01-12 13:16 UTC, reschke commented
I see. Maybe a less intrusive change would be to say:

"... The origin server SHOULD NOT perform the requested method if **the condition evaluates to false:** the selected representation's last modification date is earlier than or equal to the date provided in the field value; instead, the origin server SHOULD generate a 304 (Not Modified) response, including only those metadata that are useful for identifying or updating a previously cached response."

2021-01-12 19:41 UTC, royfielding approved these changes

2021-01-12 21:00 UTC, reschke approved these changes
(but see comments)

2021-01-12 21:00 UTC, reschke commented on draft-ietf-httpbis-semantics-latest.xml
> +      If the selected representation's last modification date is earlier or
```suggestion
      If the selected representation's last modification date is earlier than or
```

2021-01-12 21:00 UTC, reschke commented on draft-ietf-httpbis-semantics-latest.xml
> +      If the selected representation's last modification date is earlier or
```suggestion
      If the selected representation's last modification date is earlier than or
```

2021-01-12 21:07 UTC, merged