Clarify status code range (fixes #684)
httpwg/http-core pull request #717
Opened 2021-01-31 14:20 UTC by reschke

2021-01-31 18:40 UTC, royfielding requested changes
I think we need to say why they are invalid.

2021-01-31 18:40 UTC, royfielding commented on draft-ietf-httpbis-semantics-latest.xml
> +   Values outside the range 100..599 are invalid.
```suggestion
   Values outside the range 100..599 are invalid. Implementations often use three-digit
   integer values outside of that range (e.g., 600..999) for internal communication of
   non-HTTP status (e.g., library errors).
```

2021-01-31 18:40 UTC, royfielding commented on draft-ietf-httpbis-semantics-latest.xml
> +  <li>In <xref target="status.codes"/>, clarify that values outside the range 100..599 are invalid (<eref target="https://github.com/httpwg/http-core/issues/684"/>)</li>
```suggestion
  <li>In <xref target="status.codes"/>, clarify that status code values outside the range 100..599 are invalid (<eref target="https://github.com/httpwg/http-core/issues/684"/>)</li>
```

2021-01-31 23:18 UTC, mnot approved these changes

2021-01-31 23:18 UTC, mnot commented
Do we want to give any guidance about what an implementation should do when receiving an invalid code? I ask because if we don't, implementations are likely to behave in different ways.

2021-02-01 20:23 UTC, royfielding requested changes

2021-02-01 20:23 UTC, royfielding commented on draft-ietf-httpbis-semantics-latest.xml
> +   the request.
On second read, this is getting clunky and burying the definition. I'd prefer:
```suggestion
   The status code of a response is a three-digit integer code that describes the
   result of the request and the semantics of the response, including whether or
   not the request was successful and what content is enclosed (if any).
   All valid status codes for HTTP are within the range of 100 to 599, inclusive.
```

2021-02-01 20:33 UTC, royfielding commented
> Do we want to give any guidance about what an implementation should do when receiving an invalid code? I ask because if we don't, implementations are likely to behave in different ways.

I think that is application-dependent, since behavior will depend on how the user interacts with the response and whether the application is directly using HTTP or using a library that happens to use HTTP.

Perhaps

> A client that receives an invalid status code SHOULD use the response like a 500 status code.

2021-02-02 00:17 UTC, mnot commented
I think adding that would be helpful -- it gives people room for other behaviours, but suggests a sensible default handling.

2021-02-02 07:14 UTC, annevk commented
I suspect

> A client that receives an invalid status code SHOULD use the response like a 500 status code.

might be open to misinterpretation as I could see people not considering 299 to be valid, for instance. (It's in the valid range, but I suppose it needs to be registered to be truly valid?)

2021-02-02 07:33 UTC, reschke commented
> could see people not considering 299 to be valid, for instance

We really need to say that 100...599 are valid, not that all valid codes are in that range.

2021-02-02 07:38 UTC, annevk commented
> A valid status code is a status code in the range 100 to 599, inclusive.

Would make that clear, I think.

2021-02-02 07:53 UTC, reschke commented
Not really. It only says that valid codes are in 100..599, not that *all* values in that range are valid.

2021-02-02 08:06 UTC, annevk commented
I read it as defining valid status code being a status code in that range.

2021-02-02 08:16 UTC, reschke commented
You are right. I misread it.

2021-02-04 02:46 UTC, royfielding commented on draft-ietf-httpbis-semantics-latest.xml
> +   an invalid status code &SHOULD; process it as if it had a <x:ref>5xx (Server Error)</x:ref>
```suggestion
   an invalid status code &SHOULD; process the response as if it had a <x:ref>5xx (Server Error)</x:ref>
```

2021-02-04 02:47 UTC, royfielding approved these changes

2021-02-04 02:47 UTC, merged