Adjust handling of invalid Age values
httpwg/http-core pull request #781
Opened 2021-02-24 04:07 UTC by mnot

Fixes #778.

2021-02-24 12:44 UTC, reschke requested changes

2021-02-24 12:44 UTC, reschke commented on draft-ietf-httpbis-cache-latest.xml
> +   (e.g., it contains something other than a non-negative integer),
"as per above" is not longer true...

2021-02-25 05:20 UTC, reschke approved these changes

2021-02-26 00:06 UTC, royfielding approved these changes

2021-02-26 00:07 UTC, merged