Relax invalid characters in field values
httpwg/http-core pull request #783
Opened 2021-02-24 04:21 UTC by mnot

Fixes #683.

2021-02-24 12:21 UTC, reschke requested changes
I though the proposal was to go back to what RFC723* said - CTL characters are invalid, but do not require them to be rejected or converted.

2021-02-24 23:58 UTC, mnot commented
That's what this does; the text above already has that effect.

It does raise the question of whether we should add CTL to `obs-text`, however. Thoughts?

2021-02-25 05:25 UTC, reschke commented
> That's what this does; the text above already has that effect.

I believe the proposed text now is somewhat misleading, as it does *not* mention that CTLs are (and always have been invalid.

> It does raise the question of whether we should add CTL to obs-text, however. Thoughts?

No, that would be a breaking change.

2021-02-26 00:01 UTC, royfielding requested changes
How about this variation?

2021-02-26 00:01 UTC, royfielding commented on draft-ietf-httpbis-semantics-latest.xml
> +   processing or forwarding the message.
```suggestion
   Field values containing CR or NUL characters are invalid and dangerous, due
   to the varying ways that implementations might parse and interpret those characters;
   a recipient of CR or NUL within a field value &MUST; either reject the message or
   replace each of those characters with SP before further processing or forwarding
   of that message. Field values containing other CTL characters are also invalid;
   however, recipients &MAY; retain such characters for the sake of robustness if
   they only appear within safe field value contexts (e.g., data not required by HTTP).
```

2021-03-01 07:34 UTC, reschke commented
We still need to rewrite or remove

> Clarify that control characters in field values are to be rejected or mapped to SP. (Section 5.5)

2021-03-01 08:06 UTC, reschke approved these changes

2021-03-04 04:41 UTC, royfielding approved these changes

2021-03-04 04:41 UTC, merged