fix misleading statement in Acks (fixes #824)
httpwg/http-core pull request #833
Opened 2021-04-06 10:50 UTC by reschke

2021-04-06 22:24 UTC, royfielding requested changes
I think we should just properly edit the acks instead of hacking on this bit leftover from 7230.

Do we want to ack substantial contributors? If so, I will go through the old RFCs and pick out a list of substance. The last example of that is RFC2616 (based on what I wrote for 1945 and 2068). If not, we should ack all of the specs and not the individuals, instead pointing to the real acks in those specs.

2021-04-07 00:54 UTC, royfielding approved these changes
This is what I had in mind in terms of bringing back the original acks.

2021-04-07 00:55 UTC, royfielding commented
I am seeing a lot of warnings about lines being too long (longer that 72 characters), but they are unrelated to these changes.

2021-04-07 01:32 UTC, mnot approved these changes

2021-04-07 06:57 UTC, merged