clarify that Accept-Ranges can be sent by any server
httpwg/http-core pull request #902
Opened 2021-07-12 23:11 UTC by royfielding

Clarify that Accept-Ranges can be sent by any server, remove "none" from the ABNF because it is now a reserved range unit, and allow the field to be sent in a trailer section while noting why that is much less useful than as a header field

For #857 

this is an alternative to #882

2021-07-13 06:22 UTC, reschke approved these changes

2021-07-13 06:28 UTC, mnot requested changes
If we're going to do this, we need to properly account for the cases where a value has been added by a proxy, and then the client's proxy changes (either through configuration or behind the scenes).

I believe most people think of this as metadata about the resource's capabilities -- indeed, the text you just wrote make that assumption. It would be much cleaner and more useful to restrict this information to the origin server, no matter what the historical intent was. That's how it's currently used today.

If we can't agree on this, we should take it to the list.

2021-07-13 06:28 UTC, mnot commented on draft-ietf-httpbis-semantics-latest.xml
> +   Range units are defined in <xref target="range.units"/>.
This isn't necessarily true; the target resource doesn't always support them if the header was added by a proxy.

2021-07-13 06:28 UTC, mnot commented on draft-ietf-httpbis-semantics-latest.xml
> +   is reserved for this purpose.
You need to do something like this to properly qualify it for the possibility that a proxy added the value:

```suggestion
   to advise the client not to attempt a range request on the current request path. The range unit "none"
   is reserved for this purpose.
```

2021-07-13 10:17 UTC, reschke commented
> It would be much cleaner and more useful to restrict this information to the origin server, no matter what the historical intent was. That's how it's currently used today.

IMHO... allowing non-origins to service range requests, but disallowing them to advertise that is really really weird. At the end of the day, any "Accept-*" field value received is always a statement about the present, and not a promise for future requests. This is not different from other fields.

Do you believe it would actually be harmful if a client was mislead to believe it can do a range request, and then it receives the full content with a 200?

2021-07-13 17:00 UTC, royfielding commented on draft-ietf-httpbis-semantics-latest.xml
> +   to indicate that the request's target resource supports range requests,
```suggestion
   to indicate that it supports byte range requests for that target resource,
```

2021-07-13 17:02 UTC, royfielding commented on draft-ietf-httpbis-semantics-latest.xml
> +   thereby encouraging its use by the client for future partial requests.
```suggestion
   thereby encouraging its use by the client for future partial requests on
   the same request path.
```

2021-07-13 17:04 UTC, royfielding commented on draft-ietf-httpbis-semantics-latest.xml
> +   is reserved for this purpose.
```suggestion
   to advise the client not to attempt a range request on the same request path.
   The range unit "none" is reserved for this purpose.
```

2021-07-13 17:18 UTC, royfielding commented
> I believe most people think of this as metadata about the resource's capabilities -- indeed, the text you just wrote make that assumption. It would be much cleaner and more useful to restrict this information to the origin server, no matter what the historical intent was. That's how it's currently used today.

A header field is defined by the intent of the people who minted and deployed it. That was Lou Montulli. Its original meaning was confused in the pre-RFC2068 draft because of an editorial mistake, not because the header field ever changed its meaning as deployed. The main use case was restarting a big download, and that is not specific to origin servers.

Today, this field is largely ignored because of the poor specification. We can improve such things without harm.

2021-07-14 07:02 UTC, mnot commented
I don't think this is worth too much more time, I'll just say I disagree -- it's not very useful in this form, and it differs from every other bit of similar metadata we put into headers (e.g., `Allow`, `Accept-*`, `Vary`).

I'll make a suggestion to try to make the ambiguity here a bit more clear.

2021-07-14 07:02 UTC, mnot commented on draft-ietf-httpbis-semantics-latest.xml
>  <t>
```suggestion
</t>
<t>
   Conversely, a client &MUST-NOT; assume that receiving an Accept-Ranges field means that future requests
   will return partial responses. The server might not support future range requests, or the header might have
   been added by an intermediary on a different path.
</t>
<t>
```

2021-07-14 17:07 UTC, royfielding commented
> I don't think this is worth too much more time, I'll just say I disagree -- it's not very useful in this form, and it differs from every other bit of similar metadata we put into headers (e.g., `Allow`, `Accept-*`, `Vary`).

You are starting with an assumption that this is an origin characteristic and saying that this doesn't fit that assumption. I agree that the assumption does not fit the header field's definition, nor is it a fit for purpose. The field's purpose is to tell the client that range requests may help if there is a problem receiving the whole content. That's not limited to origin servers and has nothing in common with Allow or Vary.

If a proxy cache can process range requests on large cached items (e.g., a company training video) and its clients can benefit from that, why would we not want to advertise that fact to the client? The theory that this may cause a problem with multiple paths just doesn't hold for proxies (they are client chosen) and wouldn't matter anyway for range requests because the worst case is a 200 response. This was explained in 1996 and the definition was fixed in the next draft. It just wasn't fixed enough.

This doesn't change the fact that the header field isn't very useful, simply because it is advisory only and most clients will ignore that advice when it doesn't matter to them if 200 is the response. That's okay.

2021-07-14 17:15 UTC, royfielding commented on draft-ietf-httpbis-semantics-latest.xml
> +   been added by an intermediary on a different path.
```suggestion
   Conversely, a client &MUST-NOT; assume that receiving an Accept-Ranges field
   means that future range requests will return partial responses. The content might
   change, the server might only support range requests at certain times or under
   certain conditions, or a different intermediary might process the next request.
```

2021-07-14 17:32 UTC, reschke approved these changes

2021-07-14 23:00 UTC, mnot approved these changes

2021-07-14 23:12 UTC, merged