tune prose in text that references [HTTP] for status code information (#915)
httpwg/http-core pull request #922
Opened 2021-08-02 11:56 UTC by reschke

2021-08-02 17:52 UTC, royfielding requested changes
I don't think this is correct. I can try rewriting the whole sentence, if necessary.

2021-08-02 18:36 UTC, reschke commented
Please do :-)

2021-08-03 00:52 UTC, royfielding approved these changes

2021-08-03 04:26 UTC, mnot approved these changes
suggestion

2021-08-03 04:26 UTC, mnot commented on draft-ietf-httpbis-messaging-latest.xml
> +   that status code indicated by its first digit.
```suggestion
   that status code indicated by its first digit if it is not.
```

2021-08-03 07:40 UTC, merged