clarify status of redirect status codes (closes #947)
httpwg/http-core pull request #948
Opened 2021-08-11 14:33 UTC by reschke

2021-08-11 17:13 UTC, royfielding requested changes

2021-08-11 17:13 UTC, royfielding commented on draft-ietf-httpbis-semantics-latest.xml
> +    made that behavior conformant if and only if the original request is POST.
```suggestion
    &Note; In HTTP/1.0, the status codes <x:ref>301 (Moved Permanently)</x:ref>
    and <x:ref>302 (Found)</x:ref> were originally defined as method-preserving
    (<xref target="HTTP10" x:fmt="," x:sec="9.3"/>) to match their implementation
    at CERN; <x:ref>303 (See Other)</x:ref> was defined for a redirection that
    changed its method to GET. However, early user agents split on whether to
    redirect POST requests as POST (according to then-current specification)
    or as GET (the safer alternative when redirected to a different site).
    Prevailing practice eventually converged on changing the method to GET.
    <x:ref>307 (Temporary Redirect)</x:ref> and
    <x:ref>308 (Permanent Redirect)</x:ref> <xref target="RFC7538"/> were
    later added to unambiguously indicate method-preserving redirects, and
    <x:ref>301</x:ref>/<x:ref>302</x:ref> have been adjusted to allow a POST
    request to be redirected as GET.
```

2021-08-11 17:13 UTC, royfielding commented on draft-ietf-httpbis-semantics-latest.xml
> +    made that behavior conformant if and only if the original request is POST.
I think this rewrite is also needed to make the note understandable.

2021-08-12 03:35 UTC, mnot approved these changes

2021-08-12 04:02 UTC, merged