Mnot 958
httpwg/http-core pull request #963
Opened 2021-08-17 03:23 UTC by mnot

Additional instances of 'select'

Fixes #958

2021-08-17 03:23 UTC, mnot commented
I went with 'nominated' in a few places where 'choosing' didn't seem workable. 'varying' could work too, I suppose, but we'd probably need to add it as a defined term.

2021-08-17 03:40 UTC, royfielding commented
I think that "selecting header fields" was fine and reads better than nominated or chosen fields — they are the request fields that the origin claims were used to select each representation, so the name fits even if we use them later to choose a response.

2021-08-17 03:49 UTC, mnot commented on draft-ietf-httpbis-cache-latest.xml
> +   The nominated header fields from two requests are defined to match if
```suggestion
   The header fields from two requests are defined to match if
```

2021-08-17 03:51 UTC, mnot commented on draft-ietf-httpbis-cache-latest.xml
> +   If multiple stored responses match the nominated header fields
```suggestion
   If multiple stored responses match the request header fields nominated by Vary
```

2021-08-17 03:52 UTC, mnot commented
@royfielding see updates; I think I managed to avoid the awkwardness

2021-08-17 11:12 UTC, royfielding commented on draft-ietf-httpbis-cache-latest.xml
> +   by incorporating chosen values from the original request's header fields
```suggestion
   by incorporating some of the original request's header fields
```

2021-08-17 11:16 UTC, royfielding commented on draft-ietf-httpbis-cache-latest.xml
> +   (potentially including responses without a Vary header field),
```suggestion
   If multiple stored responses match,
```

2021-08-17 11:17 UTC, royfielding commented on draft-ietf-httpbis-cache-latest.xml
> +   see <xref target="age.calculations"/>) stored response with a valid Vary
```suggestion
   header field, the cache &SHOULD; choose the most recent
   (see <xref target="age.calculations"/>) stored response with a valid Vary
```

2021-08-17 11:23 UTC, royfielding requested changes

2021-08-17 11:23 UTC, royfielding commented on draft-ietf-httpbis-cache-latest.xml
> +   by incorporating chosen values from the original request's header fields
Also, the first sentence would be better as

>   A cache might store multiple responses for a request target that is subject to content negotiation.

2021-08-18 02:44 UTC, mnot commented on draft-ietf-httpbis-cache-latest.xml
>     store multiple responses for it. Caches differentiate these responses
```suggestion
   A cache might store multiple responses for a request target that is subject 
   to content negotiation. Caches differentiate these responses
```

2021-08-18 03:52 UTC, royfielding approved these changes

2021-08-18 04:00 UTC, merged

2021-09-19 18:53 UTC, mosi2021v reviewed
#